### ISSUE TITLE
Not giving any information in discord

### ISSUE THREAD

**Issue by KScroom** [doenerium6969/doenerium-fixed#30]
nothing when ran   (also too big to send in discord without nitro)
![image](https://github.com/doenerium6969/doenerium-fixed/assets/169678979/b9fe7f4c-b467-4e50-9482-96fdb0c1b472)

**Comment by doenerium6969** [comment]
you need to hack real computer no vm or rpd

**Comment by KScroom** [comment]
It's too big to send in most apps bro
